### ISSUE TITLE
Cannot make an ajax call and handling done

### ISSUE THREAD

**Issue by balazs-zsoldos** [jsweet-candies/candy-jquery#1]
I tried to make a post call with JQuery with the following code:

    $.post("", data).done(new JQueryPromiseCallback<Object>() {

      @Override
      public void $apply() {
        // TODO Auto-generated method stub

      }

      @Override
      public void $apply(final Object value, final java.lang.Object... args) {
        alert("works");
      }

    }, (JQueryPromiseCallback<?>) null);

However, this generated a typescript code that is syntactically wrong. I guess because $apply is a kind of reserved word in jsweet (means reflective function calle). Anyway, it is strange that _done_ function does not accept a functional interface but one with two methods.

The generated typescript code:

        public onsubmit(event : Event, form : HTMLFormElement) : boolean {
            let data : string = $(form).serialize();
            $.post("", data).done(() => {
            }(value : Object, ...args : any[]) => {
                alert("works");
            }, <any>(null));
            event.preventDefault();
            return false;
        }

See the missing comman on line 4 after }.

If this is not the way how it should be done, could you, please, show an example how ajax calls can be sent with JQuery and process the response?

**Comment by renaudpawlak** [comment]
I guess that the JQuery promise API is not well supported. You can always override the typing in JSweet. 
So a way to do it (ugly but should work):

```java
import static jsweet.util.Lang.function;

[...]
$.post("", data).done((JQueryPromiseCallback<?>)(function(() -> { 
    alert("done"); 
  })), (JQueryPromiseCallback<?>) null);
```

Don't hesitate to copy the JQuery JSweet definitions sources in your project and manually modify them to have better API.

**Comment by balazs-zsoldos** [comment]
Thanks for the hint. I analyzed the problem a bit and it might come from some generator in JSweet. I created an issue in the JSweet project: https://github.com/cincheo/jsweet/issues/426

**Comment by lgrignon** [comment]
I would suggest, if it is ok for you, to enhance the existing jquery candy repository. Wouldn't it be better?

**Comment by balazs-zsoldos** [comment]
@lgrignon I guess that the candy is generated with the JSweet Candy Generator. I might be wrong. However, if that is the case, the generator should be fixed first and re-generate the candy afterward.

**Comment by lgrignon** [comment]
The generator is just an help to bootstrap the candy project and generate most of the cany code, but it is now actually just a standard github repository on which anyone can contribute.
The only reason why we would reuse the generator for JQuery would be to upgrade the library definitions.
If you want to contribute, you just need to delete the empty $apply signature and push (I will add you to the related github orga)

**Comment by balazs-zsoldos** [comment]
@lgrignon I will test it and push the change soon after testing it. Thanks!
